import './styles/globals.css'
import './styles/app.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './_components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hammershift',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar isLoggedIn={true} />
        {children}
      </body>
    </html>
  )
}
