"use client";

import "./styles/globals.css";
import "./styles/app.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import { SessionProvider } from "next-auth/react";
import BetaTesting from "./components/beta_testing";
import { Analytics } from "@vercel/analytics/react";
import LoadWallet from "./components/load_wallet";
import Footer from "./components/footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Hammershift',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        {/*<body className={inter.className} */}
        <body>
          <Navbar />
          {/* <BetaTesting /> */}
          {children}
          <Analytics />
          <LoadWallet />
          <Footer />
        </body>
      </SessionProvider>
    </html>
  );
}
